[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama-runner"
version = "0.1.2"
description = "Lightweight Python client for running local Ollama models"
authors = [{ name="Prabhav Sharma" }]
dependencies = ["requests"]
requires-python = ">=3.9"
